name: Bump version

on:
  workflow_run:
    workflows: [ "Tests" ]
    branches: [ master ]
    types:
      - completed

permissions: read-all

jobs:
  bump:
    name: Bump version
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
